env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]}
